algoritmo "semnome"
//15) Crie um programa que leia o número de dias trabalhados em um mês e mostre o
//salário de um funcionário, sabendo que ele trabalha 8 horas por dia e ganha R$25
//por hora trabalhada.
var
   Dt, Dia, Salario: Real
inicio
      Escreva ("Dias trabalhados: ")
      Leia (Dt)
      Dia <- 8*25
      Salario <- Dt * Dia)
      Escreva ("Seu salário ao final de ", Dt, " dias será: R$ ", Salario:6:2)
fimalgoritmo
